[project]
name = "dansonic"
version = "0.1.0"
description = "Generates music reactively from a dancer's captured figures/motion"
authors = [
    {name = "Caglan Akpinar", email = "cakpinar23@gmail.com"}
]
readme = "../README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "opencv-python (>=4.10.0,<5.0.0)",
    "mediapipe (>=0.10.14,<0.11.0)",
    "numpy (>=1.26.0,<2.0.0)",
    "scipy (>=1.13.0,<2.0.0)",
    "sounddevice (>=0.4.7,<0.5.0)",
    "soundfile (>=0.12.1,<0.13.0)",
    "librosa (>=0.10.2,<0.11.0)",
    "pydub (>=0.25.1,<0.26.0)",
    "moviepy (>=1.0.3,<2.0.0)",
]

[tool.poetry]
packages = [
    { include = "music", from = "src" },
    { include = "motion_capture", from = "src" },
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
ipykernel = "^6.29.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
